version: '3'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pypods_database
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_INIT_CONNECT: 'SET @@GLOBAL.max_allowed_packet=64*1024*1024;'
    ports:
      - "3306:3306"
    restart: always
  pypods-imageproxy:
    image: madeofpendletonwool/pypods-imageproxy:latest
    ports:
      - "8000:8000"
    restart: always
  # pypods:
  #   image: madeofpendletonwool/pypods:latest
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db
  #     - pypods-imageproxy
