version: '3'
services:
  db:
    image: mariadb:latest
    command: --wait_timeout=1800
    environment:
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_PASSWORD: myS3curepass
      MYSQL_DATABASE: pypods_database
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_INIT_CONNECT: 'SET @@GLOBAL.max_allowed_packet=64*1024*1024;'
    volumes:
      - /home/user/pinepods/sql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  pinepods:
    image: madeofpendletonwool/pinepods:latest
    ports:
    # Web Portal Port
      - "8034:8034"
    # API Server Port - Needed for Client Connections
      - "8032:8032"
    # Image Proxy Port - Needed to Display Some Images
      - "8000:8000"
    environment:
      # Default Admin User Information
      USERNAME: myadminuser01
      PASSWORD: myS3curepass
      FULLNAME: Pinepods Admin
      EMAIL: user@pinepods.online
      # Database Vars
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: myS3curepass
      DB_NAME: pypods_database
      # Image/Audio Proxy Vars
      PROXY_HOST: proxy.pinepods.online
      PROXY_PORT: 8000
      PROXY_PROTOCOL: https
      REVERSE_PROXY: "True"
      # Search Index API Vars
      API_URL: 'https://search.pinepods.online/api/search'
      # Client API Vars
      API_SERVER_PORT: 8032
    volumes:
    # Mount the download location on the server if you want to. You could mount a nas to this folder or something like that
      - /home/user/pinepods/downloads:/opt/pypods/downloads

    depends_on:
      - db