version: '3'
services:
    pypods-backend:
       image: madeofpendletonwool/pinepods_backend:latest
       container_name: pypods-be
       environment:
           - API_KEY=your_api_key
           - API_SECRET=your_api_secret
       ports:
            - 5000:5000
       restart: unless-stopped