{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinepods.fullname" . }}-backend
  labels:
    {{- include "pinepods.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pinepods.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}