apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: { { .Values.persistence.size } }
  accessModes:
    - { { .Values.persistence.accessMode } }
  hostPath:
    path: "/home/user/pgdata"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - { { .Values.persistence.accessMode } }
  resources:
    requests:
      storage: { { .Values.persistence.size } }
