apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinepods.fullname" . }}-env
  labels:
    {{- include "pinepods.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
