apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinepods.fullname" . }}-secret
  labels:
    {{- include "pinepods.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
