{{- /* Set default environment variables. */ -}}
{{ $env := dict -}}
{{ $_ := set $env "DB_HOST" (include "pinepods.postgresql.fullname" .) }}
{{ $_ := set $env "VALKEY_HOST" (include "pinepods.valkey.fullname" .) }}
{{ $_ := set $env "VALKEY_PORT" (.Values.valkey.service.port) }}

{{- /* Merge in user-specified environment variables, overriding the above. */ -}}
{{ $env := mergeOverwrite $env .Values.env -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinepods.fullname" . }}-env
  labels:
    {{- include "pinepods.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := $env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
