apiVersion: v2
name: pinepods
version: 0.1.0
description: A Helm chart for deploying Pinepods - A complete podcast management system and allows you to play, download, and keep track of podcasts you enjoy. All self hosted and enjoyed on your own server!
dependencies:
  - name: postgresql
    version: 15.5.14
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: valkey
    version: 2.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: valkey.enabled