replicaCount: 2

image:
  repository: pinepods
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8040
  nodePort: 30007

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

postgresql:
  enabled: true
  auth:
    username: postgres
    password: "supersecretpassword"
    database: pinepods_database
  primary:
    persistence:
      enabled: true
      existingClaim: postgres-pvc

env:
  SEARCH_API_URL: "https://search.pinepods.online/api/search"
  USERNAME: "admin"
  PASSWORD: "password"
  FULLNAME: "Admin User"
  EMAIL: "admin@example.com"
  DB_TYPE: "postgresql"
  DB_HOST: "pinepods-postgresql.pinepods-namespace.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "pinepods_database"
  DEBUG_MODE: "false"
