name: Build Pinepods Flatpak

on:
  workflow_run:
    workflows: ["Build Tauri Clients"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (for testing)"
        required: true
        default: "test"

env:
  FLATPAK_ID: com.gooseberrydevelopment.pinepods

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder appstream

      - name: Install Flatpak SDK
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.gnome.Platform//46 org.gnome.Sdk//46

      - name: Update manifest version and URL
        run: |
          sed -i "s|url: .*|url: https://github.com/${{ github.repository }}/releases/download/$VERSION/pinepods_${VERSION}_amd64.deb|" clients/flatpak/com.gooseberrydevelopment.pinepods.yml
          DEB_URL=$(grep url clients/flatpak/com.gooseberrydevelopment.pinepods.yml | awk '{print $2}')
          SHA256=$(curl -sL $DEB_URL | sha256sum | cut -d' ' -f1)
          sed -i "s|sha256: .*|sha256: $SHA256|" clients/flatpak/com.gooseberrydevelopment.pinepods.yml

      - name: Get shared Modules
        run: |
          git clone https://github.com/flathub/shared-modules

      # Test build steps
      - name: Build and test Flatpak
        run: |
          flatpak-builder --force-clean --sandbox --user --install-deps-from=flathub --ccache \
              --mirror-screenshots-url=https://dl.flathub.org/media/ --repo=repo builddir \
              clients/flatpak/com.gooseberrydevelopment.pinepods.yml

          flatpak remote-add --user --no-gpg-verify test-repo "$(pwd)/repo"
          flatpak install --user -y test-repo ${{ env.FLATPAK_ID }}

          # Basic launch test (timeout after 30s)
          timeout 30s flatpak run ${{ env.FLATPAK_ID }} || true

          # Verify metainfo
          flatpak run --command=cat ${{ env.FLATPAK_ID }} \
              /app/share/metainfo/${{ env.FLATPAK_ID }}.metainfo.xml

      - name: Create Flatpak bundle
        run: |
          flatpak build-bundle repo ${{ env.FLATPAK_ID }}.flatpak ${{ env.FLATPAK_ID }}

      # Archive everything needed for the Flathub PR
      - name: Archive Flatpak files
        run: |
          mkdir flatpak_output
          cp ${{ env.FLATPAK_ID }}.flatpak flatpak_output/
          cp clients/flatpak/com.gooseberrydevelopment.pinepods.yml flatpak_output/
          cp clients/flatpak/${{ env.FLATPAK_ID }}.metainfo.xml flatpak_output/
          tar -czvf flatpak_files.tar.gz flatpak_output

      - name: Upload Flatpak archive
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-files
          path: flatpak_files.tar.gz