# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create Pinepods Windows Client

on:
  pull_request:
    branches: [ "main" ]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create Windows Client
      run: |
        flet pack clients/windows-app/pinepods.py --icon clients/windows-app/assets/pinepods-appicon.png --add-data "clients/windows-app/assets;assets" --product-name "Pinepods" --product-version "0.1" --copyright "More like Copyleft amiright?" --file-description "A Forest of Podcasts, Rooted in the Spirit of Self-Hosting" --file-version "0.1"
        
        
#     - name: Get Latest Tag
#       uses: madeofpendletonwool/pinepods@v1

    - name: Archive Pinepods Windows Client Release
      uses: actions/upload-artifact@v3
      with:
        name: Pinepods-Windows
        path: dist/pinepods.exe
