name: Notifications on release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      message_text:
        description: "Manual override text (optional)"
        required: false

jobs:
  discord_announcement:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set release message
        id: set_message
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            version="${{ github.event.release.tag_name }}"
            message="Pinepods Version $version Released! Check out the release [here](${{ github.event.release.html_url }})"
            echo "::set-output name=message::$message"
          else
            echo "::set-output name=message::${{ github.event.inputs.message_text }}"
          fi


      - name: Discord notification to announce deployment
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: ${{ steps.set_message.outputs.message }}
