name: Update AUR Package

on:
  workflow_run:
    workflows: ["Build Tauri Clients"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g. 0.6.6)"
        required: true

jobs:
  update-aur-package:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            # Extract version from the triggering release
            RELEASE_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
            echo "VERSION=$RELEASE_TAG" >> $GITHUB_ENV
          fi

      - name: Generate PKGBUILD
        run: |
          # Calculate checksums for both architectures
          x86_64_url="https://github.com/madeofpendletonwool/PinePods/releases/download/$VERSION/Pinepods_${VERSION}_amd64.deb"
          aarch64_url="https://github.com/madeofpendletonwool/PinePods/releases/download/$VERSION/Pinepods_${VERSION}_arm64.deb"

          x86_64_sum=$(curl -sL "$x86_64_url" | sha256sum | cut -d' ' -f1)
          aarch64_sum=$(curl -sL "$aarch64_url" | sha256sum | cut -d' ' -f1)

          cat > PKGBUILD << EOF
pkgname=pinepods
pkgver=$VERSION
pkgrel=1
pkgdesc="Pinepods is a complete podcast management system and allows you to play, download, and keep track of podcasts you enjoy. All self hosted and enjoyed on your own server!"
arch=('x86_64' 'aarch64')
url="https://github.com/madeofpendletonwool/PinePods"
license=('gpl3')
depends=('cairo' 'desktop-file-utils' 'gdk-pixbuf2' 'glib2' 'gtk3' 'hicolor-icon-theme' 'libsoup' 'pango' 'webkit2gtk')
options=('!strip' '!emptydirs')
install=\${pkgname}.install
source_x86_64=("https://github.com/madeofpendletonwool/PinePods/releases/download/\$pkgver/Pinepods_\$pkgver\_amd64.deb")
source_aarch64=("https://github.com/madeofpendletonwool/PinePods/releases/download/\$pkgver/Pinepods_\$pkgver\_arm64.deb")
sha256sums_x86_64=('$x86_64_sum')
sha256sums_aarch64=('$aarch64_sum')
EOF

      - name: Copy install file
        run: cp clients/aur/pinepods.install ./

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v3.0.1
        with:
          pkgname: pinepods
          pkgbuild: ./PKGBUILD
          assets: pinepods.install
          commit_username: ${{ secrets.GIT_USER }}
          commit_email: ${{ secrets.GIT_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version ${{ env.VERSION }}"
          ssh_keyscan_types: rsa,ecdsa,ed25519
