[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#trunk = "0.18.0"
#yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
#yew = { "0.21.0", features = ["csr"] }
web-sys = { version = "0.3.66", features = ["CssStyleDeclaration"] }
log = "0.4.20"
wasm-bindgen = "0.2.89"
yew-router = { git = "https://github.com/yewstack/yew.git" }